### ISSUE TITLE
Error2 the system cannot find the file specified

### ISSUE THREAD

**Issue by afahs** [afahs/PingChecker#2]
Traceback (most recent call last):
  File "C:\Users\Adam\Documents\GitHub\PingChecker\ping_checker.py", line 11, in <module>
    proc=Popen(['pip2','install','pyping'],stdout=PIPE,stderr=PIPE)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by omegalink12** [comment]
Make sure pip2 is in your path
Or call in python install directory
